name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: ["Build"]  # Name of the first workflow
    types:
      - completed
env:
    REGISTRY_URL: "https://registry.digitalocean.com/zedwerks"
    REGISTRY: registry.digitalocean.com/zedwerks
    IMAGE_NAME: keycloak-smart-fhir
    DROPLET_NAME: smart-kc
    DROPLET_REGION: canada
    DROPLET_SIZE: s-1vcpu-1gb

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract short SHA referencing the image tag
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::8}"

      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.99.0/doctl-1.99.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin
      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
        run: doctl auth init -t $DIGITALOCEAN_API_TOKEN

      - name: Create Droplet
        id: create_droplet
        env:
          DROPLET_NAME: ${{ env.DROPLET_NAME }}
          DROPLET_REGION: ${{ env.DROPLET_REGION }}
          DROPLET_SIZE: ${{ env.DROPLET_SIZE }}
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          DROPLET_KEYS: ${{ secrets.DO_SSH_KEY_FINGERPRINT }}
        run: |
          doctl compute droplet create $DROPLET_NAME \
            --region $DROPLET_REGION \
            --size $DROPLET_SIZE \
            --image docker-20-04 \
            --ssh-keys $DROPLET_KEYS \
            --wait \
            --format ID,PublicIPv4 \
            --no-header \
            --output json > droplet.json

          DROPLET_IP=$(jq -r '.[0].PublicIPv4' droplet.json)
          echo "DROPLET_IP=${DROPLET_IP}" >> $GITHUB_ENV

      - name: Wait for Droplet SSH
        id: wait_for_ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            until nc -zv -w30 $HOST 22; do
              echo "Waiting for SSH..."
              sleep 5
            done

      - name: SSH into Droplet and Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            doctl registry login -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}
            docker run -d --name ${{ env.IMAGE_NAME }} -p 80:8080 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
